import Header from "./components/Header";
import "./globals.css";
import { Providers } from "./providers";
import type { Metadata } from "next";
import { Rubik, Karla } from "next/font/google";

const inter = Rubik({ subsets: ["latin"] });
const karla = Karla({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${karla.className}`}>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
